development:
  host: demo.dspace.org
  port:
  bitstreams_path: 'public/images'

test:
  host: localhost
  port: 8443
  bitstreams_path: 'public/images'

production:
  host: demo.dspace.org
  port:
  bitstreams_path: 'public/images'
