development:
  host: localhost
  port: 8443
  # host: demo.dspace.org
  # port:
  login: dspacedemo+admin@gmail.com
  password: dspace
  bitstreams_path: 'public/images'

test:
  host: mecdb3.c3sl.ufpr.br
  port: 8443
  login: admin
  password: password
  bitstreams_path: 'public/images'
