development:
  host: demo.dspace.org
  port: 8443
  login: dspacedemo+admin@gmail.com
  password: dspace
  bitstreams_path: 'public/images'

test:
  host: portalmecdev.c3sl.ufpr.br
  port: 8443
  login: admin
  password: password
  bitstreams_path: 'public/images'
